#[test]
fn scanner_reports_ignored_dirs_and_generated_header_surfaces() {
    let repo = TempDir::new().expect("repo tempdir");
    let cache = TempDir::new().expect("cache tempdir");
    git(repo.path(), &["init", "-q"]);
    git(repo.path(), &["config", "user.email", "a@example.com"]);
    git(repo.path(), &["config", "user.name", "a"]);
    write(
        &repo.path().join("package.json"),
        r#"{"name":"scanner-policy-fixture","private":true}"#,
    );
    write(&repo.path().join(".gitignore"), "dist/\n");
    write(
        &repo.path().join("src/app.ts"),
        "import { generatedClient } from './generated/client';\n\nexport const app = generatedClient;\n",
    );
    write(
        &repo.path().join("src/generated/client.ts"),
        "/* Code generated by OpenAPI Generator. DO NOT EDIT. */\nexport const generatedClient = true;\n",
    );
    write(
        &repo.path().join("node_modules/noise/index.ts"),
        "export const dependencySource = true;\n",
    );
    write(
        &repo.path().join("vendor/noise/index.ts"),
        "export const vendoredSource = true;\n",
    );
    write(
        &repo.path().join("dist/ignored.ts"),
        "export const ignoredBuildOutput = true;\n",
    );
    git(repo.path(), &["add", "."]);
    git(repo.path(), &["add", "-f", "node_modules/noise/index.ts"]);
    git(repo.path(), &["commit", "-qm", "scanner policy fixture"]);

    let files = run_json(repo.path(), cache.path(), &["files", "--format", "json"]);
    assert_schema("schemas/files.schema.json", &files);
    let indexed = files["files"].as_array().expect("indexed files");
    assert!(
        indexed
            .iter()
            .all(|file| !file.as_str().unwrap_or_default().starts_with("node_modules/")
                && !file.as_str().unwrap_or_default().starts_with("vendor/")
                && !file.as_str().unwrap_or_default().starts_with("dist/")),
        "ignored dependency/vendor/build dirs should not become source files: {files:#}"
    );
    assert!(
        indexed
            .iter()
            .any(|file| file == "src/generated/client.ts"),
        "generated files are still visible as explicit surfaces: {files:#}"
    );

    let generated = run_json(
        repo.path(),
        cache.path(),
        &["ls", "src/generated/client.ts", "--format", "json"],
    );
    assert_schema("schemas/ls.schema.json", &generated);
    assert!(
        generated["anchor"]["roles"]
            .as_array()
            .expect("roles")
            .iter()
            .any(|role| role == "generated"),
        "generated header/path should mark the file as generated: {generated:#}"
    );

    let doctor = run_json(repo.path(), cache.path(), &["doctor", "--format", "json"]);
    assert_schema("schemas/status.schema.json", &doctor);
    assert_eq!(doctor["schema_version"], "4");
    assert!(
        doctor["scanner"]["ignored"]
            .as_array()
            .expect("ignored groups")
            .iter()
            .any(|group| group["reason"] == "common_ignore_dir:node_modules"
                && group["count"] == 1
                && group["examples"]
                    .as_array()
                    .expect("node_modules examples")
                    .iter()
                    .any(|example| example == "node_modules")),
        "doctor should explain ignored dependency dirs: {doctor:#}"
    );
    assert!(
        doctor["scanner"]["ignored"]
            .as_array()
            .expect("ignored groups")
            .iter()
            .any(|group| group["reason"] == "common_ignore_dir:vendor"
                && group["count"] == 1
                && group["examples"]
                    .as_array()
                    .expect("vendor examples")
                    .iter()
                    .any(|example| example == "vendor")),
        "doctor should explain ignored vendor dirs: {doctor:#}"
    );
    assert!(
        doctor["scanner"]["generated"]
            .as_array()
            .expect("generated groups")
            .iter()
            .any(|group| group["count"] == 1
                && group["examples"]
                    .as_array()
                    .expect("generated examples")
                    .iter()
                    .any(|example| example == "src/generated/client.ts")),
        "doctor should surface generated file groups: {doctor:#}"
    );
}
