// Responsibility: repo-roles-generated
use crate::model::FileInfo;
use crate::repo::{TEXT_EXTS, is_source_ext};
use std::fs;
use std::path::Path;

pub(crate) fn is_generated(rel: &str) -> bool {
    rel.contains(".generated.")
        || rel.contains(".gen.")
        || rel.contains("/generated/")
        || rel.ends_with(".pb.go")
        || rel.ends_with(".g.dart")
}

pub(crate) fn has_generated_header(root: &Path, info: &FileInfo) -> bool {
    if info.content_hash.is_none() {
        return false;
    }
    if !is_source_ext(&info.ext) && !TEXT_EXTS.iter().any(|ext| ext == &info.ext) {
        return false;
    }
    let Ok(text) = fs::read_to_string(root.join(&info.rel)) else {
        return false;
    };
    let header = text
        .lines()
        .take(8)
        .map(str::to_ascii_lowercase)
        .collect::<Vec<_>>()
        .join("\n");
    header.contains("@generated")
        || header.contains("code generated")
        || header.contains("auto-generated")
        || header.contains("autogenerated")
        || (header.contains("generated") && header.contains("do not edit"))
}
